# Generated by Django 4.2.3 on 2023-07-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.TextField()),
                ('transcode', models.TextField()),
            ],
            options={
                'verbose_name': 'Status Payment',
                'verbose_name_plural': 'Status Payments',
            },
        ),
    ]
