# Generated by Django 4.2 on 2023-07-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentconfirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
