# Generated by Django 4.2 on 2023-08-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_paymentdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='user',
            new_name='email',
        ),
    ]
