# Generated by Django 4.2 on 2023-08-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_rename_email_paymentdetails_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='StatusPayment',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
