# Generated by Django 4.2.3 on 2023-07-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcategory',
            name='section',
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='heading',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
