# Generated by Django 4.2 on 2023-07-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_myresults_delete_userresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='opt_5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='opt_6',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='opt_7',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='opt_1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='opt_2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='opt_3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='opt_4',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='right_opt',
            field=models.CharField(max_length=500),
        ),
    ]
