# Generated by Django 4.2 on 2023-07-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quizquestion_opt_5_quizquestion_opt_6_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quizcategory',
            name='paper_type',
        ),
        migrations.RemoveField(
            model_name='quizcategory',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='quizcategory',
            name='year',
        ),
    ]
