# Generated by Django 4.2 on 2023-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_quizcategory_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcategory',
            name='type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
