# Generated by Django 4.2 on 2023-07-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quizcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='type',
            field=models.CharField(blank=True, choices=[('free', 'free'), ('paid', 'paid')], default='paid', max_length=500, null=True),
        ),
    ]
