# Generated by Django 4.2 on 2023-08-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quizcategory'),
        ),
    ]
